name: Mis Tests Orangehrm

on:
  push:
    branches:
      - main

jobs:
  correr-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar mi código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar mis librerías
        run: pip install -r requirements.txt

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Correr los tests
        run: behave features/ -D BROWSER=chrome -f allure_behave.formatter:AllureFormatter -o reports/
        env:
          DISPLAY: ':99'

      - name: Subir reporte
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-tests
          path: reports/
          retention-days: 7
